language: python
python:
  - "2.7"
  # nightly build
# command to install dependencies

# command to run tests
install:
  - pip install codecov

# Run the unit test
script:
  - coverage run Test.py

# Push the results back to codecov
after_success:
  - codecov
